### ISSUE TITLE
use disk:getCacheKey()must match regex [a-z0-9_-]{1,64}: 

### ISSUE THREAD

**Issue by captain-miao** [rdrobinson3/VolleyImageCacheExample#3]
07-17 21:36:36.430  11625-11625/? E/AndroidRuntime: FATAL EXCEPTION: main
        java.lang.IllegalArgumentException: keys must match regex [a-z0-9_-]{1,64}: "#W0#H0http://img.nian.so/dream/3_1364733573.jpg!dream"
        at com.jakewharton.disklrucache.DiskLruCache.validateKey(DiskLruCache.java:660)
        at com.jakewharton.disklrucache.DiskLruCache.get(DiskLruCache.java:406)
        at com.dahuo.nian.net.images.DiskLruImageCache.getBitmap(DiskLruImageCache.java:108)

**Comment by dieselsaurav** [comment]
Getting same issue, anybody got the DiskCaching working??

**Comment by rdrobinson3** [comment]
I wrote this when Volley was first announced (before there was a lot of documentation available). The approach using the disk cache really isn't recommended as Volley is in fact disk caching images for you. I have some misgivings about the Volley documentation and its configurability but it should suit in most cases. I wrote a blog detailing the new findings some time ago: http://www.thekeyconsultant.com/2013/06/update-volley-image-cache.html . 

I apologize for the confusion here. Also, I am working on a fix for the broken key generation. Essentially you just need to generate a key value that fits the criteria listed in the log. Check out the createKey function in the ImageCacheManager.

**Comment by az4mxl** [comment]
The createKey function in the ImageCacheManager doesn‘t used！

**Comment by ewhite-dev** [comment]
@AZ-xml  two things: 
1) Yes that function doesn't get called because the disklruimagecache does not use imagecachemanager so you have to add the createKey function to the disklruimagecache class and change two lines "snapshot = mDiskCache.get( key );" to "snapshot = mDiskCache.get( createKey(key) );"  and "editor = mDiskCache.edit( key );" to "editor = mDiskCache.edit( createKey(key) );" , so that is the necessary patch

2) No, this will not solve your performance problems because JakeWharton's DiskLruCache blocks and will make your listview adapter load slow and jerky. @rdrobinson3 has since decided to use Volley's own internal disk caching. This example project should be updated because it is very misleading and the memory cache does not solve out of memory errors on its own

**Comment by 1hakr** [comment]
I have created a disk cache based on DiskLruCache and it works. It also solves the performance as its L2 cache and not L1 cache. You are welcome to try it out. Hope it helps.
https://github.com/DWorkS/VolleyPlus

**Comment by ipsycodex** [comment]
Working perfectly thx, Only thing is to change on line 106 of DiskLruImageCache to
snapshot = mDiskCache.get( key ); 
to
snapshot = mDiskCache.get( String.valueOf(key.hashCode()));
and on line 70
editor = mDiskCache.edit( key );
to
editor = mDiskCache.edit( String.valueOf(key.hashCode()));

Issue is happening because the key coming from volley library is basically string containing # and uppercase.
